bot:
  name: ChargingNetworkBot
  token: 7066424212:AAEYnRLay_IfdvmufZBp8BeFilkKzMLhQqc
logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  mvc:
    hiddenMethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:18000/ChargingNetwork
    username: charging_network_app
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create-drop