CREATE TABLE IF NOT EXISTS Users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    uid VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS User_passwords (
    password_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL UNIQUE REFERENCES Users(user_id),
    password text NOT NULL
);

CREATE TABLE IF NOT EXISTS Roles (
    role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL,
)

CREATE TABLE IF NOT EXISTS Users_roles (
    user_role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES Users(user_id),
    role_id INT NOT NULL REFERENCES Roles(role_id)
);

CREATE TABLE IF NOT EXISTS Addresses (
    address_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(50) NOT NULL,
    street VARCHAR(255) NOT NULL,
    house_number INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Vendors (
    vendor_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    phone_support_service VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS Stations (
    station_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_id INT NOT NULL REFERENCES Users(user_id),
    vendor_id INT NOT NULL REFERENCES Vendors(vendor_id),
    address_id INT NOT NULL REFERENCES Addresses(address_id),
    station_state VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS Charge_sessions (
    session_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES Users(user_id),
    station_id INT NOT NULL REFERENCES Stations(station_id),
    start_time TIMESTAMP NOT NULL,
    stop_time TIMESTAMP,
    stop_reason VARCHAR(20)
);
