@startuml
'https://plantuml.com/sequence-diagram

entity User {
    user_id
    --
    username
    --
    first_name
    --
    last_name
    --
    uid
}

entity User_password {
    password_id
    --
    user_id
    --
    password
}

entity User_role {
    role_id
    --
    user_id
}

entity Role {
    role_id
    --
    role_name
}

entity Address {
    address_id
    --
    city
    --
    street
    --
    house_number
}

entity Vendor {
    vendor_id
    --
    company_name
    --
    phone_support_service
}

entity Station {
   station_id
   --
   manager_id
   --
   vendor_id
   --
   address_id
   --
   station_state
}

entity Charge_session {
    session_id
    --
    user_id
    --
    station_id
    --
    start_time
    --
    stop_time
    --
    stop_reason
}

User -- Station
User -- User_password
User -- User_role
User_role -- Role
User -- Charge_session
Address -- Station
Vendor -- Station
Station -- Charge_session

@enduml